######################################################################
# Automatically generated by qmake (3.0) Fri Jan 9 10:57:14 2015
######################################################################

TEMPLATE = app
TARGET = discrete
INCLUDEPATH += .
QMAKE_CFLAGS += -std=c99

# Input
SOURCES += \
    main.c
